version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    reviewers:
      - "LedgerHQ/live-devices"
    commit-message:
      prefix: "⬆️ (ci) [NO-ISSUE]: "
  # Maintain dependencies for pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
    reviewers:
      - "LedgerHQ/live-devices"
    commit-message:
      prefix: "⬆️ (repo) [NO-ISSUE]: "
