version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "github-actions"
      - "dependencies"
    reviewers:
      - "LedgerHQ/live-devices"
  # Maintain dependencies for pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "pnpm"
      - "dependencies"
    reviewers:
      - "LedgerHQ/live-devices"
