version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Paris"
    labels:
      - "dependencies"
    reviewers:
      - "LedgerHQ/live-devices"
    commit-message:
      prefix: "⬆️ (ci) [NO-ISSUE]: "
    groups:
      actions:
        patterns:
         - "*"

  # Maintain dependencies for pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Paris"
    labels:
      - "dependencies"
    reviewers:
      - "LedgerHQ/live-devices"
    commit-message:
      prefix: "⬆️ (repo) [NO-ISSUE]: "
    groups:
      eslint:
        patterns:
         - "eslint*"
         - "@eslint*"
         - "typescript-eslint*"
      changesets:
        patterns:
         - "@changesets*"
      vitest:
        patterns:
         - "vitest*"
         - "@vitest*"
      typescript:
        patterns:
         - "typescript*"
        exclude-patterns:
          - "typescript-eslint"
    ignore:
      - dependency-name: "purify-ts"
        versions: [2.1.1] # https://github.com/gigobyte/purify/releases/tag/v2.1.1 Broken ESM build
