packages:
  - apps/*
  - packages/*
  - packages/config/*
  - packages/signer/*
  - packages/tools/*
  - packages/transport/*
  - packages/trusted-apps/*

catalog:
  "@babel/core": ^7.25.2
  "@babel/preset-env": ^7.25.3
  "@babel/runtime": ^7.28.3
  "@changesets/changelog-github": 0.5.1
  "@changesets/cli": 2.29.6
  "@eslint/compat": 1.3.2
  "@eslint/core": 0.15.2
  "@eslint/js": 9.34.0
  "@inquirer/prompts": ^7.3.3
  "@ledgerhq/native-ui": ^0.27.1
  "@ledgerhq/react-ui": ^0.17.0
  "@playwright/test": ^1.49.0
  "@react-native-community/cli": 15.0.1
  "@react-native-community/cli-platform-android": 15.0.1
  "@react-native-community/cli-platform-ios": 15.0.1
  "@react-native/babel-preset": 0.81.0
  "@react-native/codegen": ^0.76.6
  "@react-native/eslint-config": 0.76.6
  "@react-native/gradle-plugin": ^0.76.6
  "@react-native/metro-config": 0.76.6
  "@react-native/typescript-config": 0.76.6
  "@react-navigation/bottom-tabs": ^7.2.0
  "@react-navigation/material-top-tabs": ^7.1.0
  "@react-navigation/native": ^7.0.14
  "@react-navigation/native-stack": ^7.2.0
  "@react-navigation/stack": ^7.1.1
  "@reduxjs/toolkit": ^2.11.2
  "@sentry/minimal": 6.19.7
  "@sentry/nextjs": ^9.33.0
  "@solana/spl-token": ^0.4.13
  "@solana/web3.js": ^1.98.2
  "@statelyai/inspect": ^0.4.0
  "@tsconfig/react-native": ^3.0.5
  "@tsconfig/recommended": ^1.0.8
  "@types/crypto-js": ^4.2.0
  "@types/node": 22.10.1
  "@types/react": 18.3.12
  "@types/react-dom": 18.3.1
  "@types/react-lottie": ^1.2.10
  "@types/react-test-renderer": ^18.0.0
  "@types/semver": 7.7.0
  "@types/styled-components": ^5.1.25
  "@types/styled-components-react-native": ^5.2.5
  "@types/uuid": ^10.0.0
  "@types/w3c-web-hid": ^1.0.6
  "@types/web-bluetooth": ^0.0.20
  "@types/ws": ^8.5.14
  "@vitejs/plugin-react": ^5.0.0
  "@vitest/coverage-istanbul": ^3.2.4
  autoprefixer: ^10.4.17
  axios: 1.13.2
  babel-plugin-module-resolver: ^5.0.2
  bitcoinjs-lib: ^6.1.6
  bs58: ^6.0.0
  buffer: ^6.0.3
  commander: ^14.0.1
  concurrently: ^9.1.0
  crypto-js: ^4.2.0
  danger: 13.0.4
  esbuild: 0.25.4
  esbuild-node-externals: 1.18.0
  eslint: 9.34.0
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-simple-import-sort: 12.1.1
  ethers: 6.14.1
  gitmoji-cli: ^9.5.0
  globals: 16.0.0
  hygen: ^6.2.11
  inversify: 7.5.1
  isomorphic-ws: ^5.0.0
  js-base64: ^3.7.8
  js-flipper: ^0.273.0
  jsdom: ^26.0.0
  next: 14.2.26
  nextra: ^3.0.13
  nextra-theme-docs: ^3.0.15
  postcss: ^8.5.6
  prettier: 3.5.3
  purify-ts: 2.1.0
  react: 18.3.1
  react-dom: 18.3.1
  react-lottie: ^1.2.10
  react-medium-image-zoom: 5.1.8
  react-native: 0.76.6
  react-native-ble-plx: 3.4.0
  react-native-gesture-handler: ^2.29.1
  react-native-get-random-values: ^1.11.0
  react-native-pager-view: ^6.7.0
  react-native-reanimated: 3.16.1
  react-native-safe-area-context: ^5.6.1
  react-native-screens: 4.4.0
  react-native-svg: ^15.11.1
  react-redux: ^9.2.0
  react-test-renderer: 18.3.1
  reflect-metadata: 0.2.2
  rimraf: ^6.0.1
  rxjs: 7.8.2
  semver: 7.7.2
  styled-components: ^5.3.11
  tailwind-merge: ^1.14.0
  tailwindcss: 3.4.16
  ts-node: 10.9.2
  tsc-alias: ^1.8.10
  turbo: ^2.3.3
  typescript: 5.9.2
  typescript-eslint: 8.41.0
  tsx: 4.19.2
  url: ^0.11.4
  util: ^0.12.5
  uuid: 11.0.3
  vitest: 3.2.4
  vitest-react-native: ^0.1.5
  ws: ^8.18.0
  xstate: 5.19.2
  zx: 8.5.3

onlyBuiltDependencies:
  - esbuild
