sonar.projectKey=LedgerHQ_device-sdk-ts
sonar.organization=ledger
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.newCode.referenceBranch=develop

sonar.sources=\
  packages/device-management-kit,\
  packages/ledger-wallet,\
  packages/mockserver-client,\
  packages/speculos-device-controller,\
  packages/ui,\
  packages/signer/context-module,\
  packages/signer/signer-aleo,\
  packages/signer/signer-btc,\
  packages/signer/signer-concordium,\
  packages/signer/signer-cosmos,\
  packages/signer/signer-eth,\
  packages/signer/signer-hyperliquid,\
  packages/signer/signer-icp,\
  packages/signer/signer-polkadot,\
  packages/signer/signer-solana,\
  packages/signer/signer-utils,\
  packages/signer/signer-zcash,\
  packages/transport/mockserver,\
  packages/transport/node-hid,\
  packages/transport/rn-ble,\
  packages/transport/rn-hid,\
  packages/transport/speculos,\
  packages/transport/web-ble,\
  packages/transport/web-hid,\
  packages/trusted-apps/ledger-keyring-protocol

sonar.javascript.lcov.reportPaths=\
  packages/device-management-kit/coverage/lcov.info,\
  packages/ledger-wallet/coverage/lcov.info,\
  packages/mockserver-client/coverage/lcov.info,\
  packages/speculos-device-controller/coverage/lcov.info,\
  packages/signer/context-module/coverage/lcov.info,\
  packages/signer/signer-aleo/coverage/lcov.info,\
  packages/signer/signer-btc/coverage/lcov.info,\
  packages/signer/signer-concordium/coverage/lcov.info,\
  packages/signer/signer-cosmos/coverage/lcov.info,\
  packages/signer/signer-eth/coverage/lcov.info,\
  packages/signer/signer-hyperliquid/coverage/lcov.info,\
  packages/signer/signer-icp/coverage/lcov.info,\
  packages/signer/signer-polkadot/coverage/lcov.info,\
  packages/signer/signer-solana/coverage/lcov.info,\
  packages/signer/signer-utils/coverage/lcov.info,\
  packages/signer/signer-zcash/coverage/lcov.info,\
  packages/transport/mockserver/coverage/lcov.info,\
  packages/transport/node-hid/coverage/lcov.info,\
  packages/transport/rn-ble/coverage/lcov.info,\
  packages/transport/rn-hid/coverage/lcov.info,\
  packages/transport/speculos/coverage/lcov.info,\
  packages/transport/web-ble/coverage/lcov.info,\
  packages/transport/web-hid/coverage/lcov.info,\
  packages/trusted-apps/ledger-keyring-protocol/coverage/lcov.info

sonar.exclusions=\
  **/node_modules/**,\
  **/coverage/**,\
  **/lib/**,\
  **/.next,\
  **/.turbo/**,\
  **/pocs/**,\
  **/_templates/**,\
  **/*.jar,\
  **/*.class

sonar.coverage.exclusions=\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/*.stub.ts,\
  **/*.stub.tsx,\
  **/*.mock.ts,\
  **/*.mock.tsx,\
  **/__tests__/**,\
  **/__mocks__/**,\
  **/*.kt
