name: "Setup toolchain with pnpm cache"
description: "Setup toolchain and restore pnpm dependencies cache"

runs:
  using: "composite"
  steps:
    - uses: moonrepo/setup-toolchain@v0

    - name: Install toolchain and setup PATH
      shell: bash
      run: |
        proto use
        # Get actual binary directories and add to PATH
        echo "$(dirname $(proto bin node))" >> $GITHUB_PATH
        echo "$(dirname $(proto bin pnpm))" >> $GITHUB_PATH
        echo "/home/runner/.proto/bin" >> $GITHUB_PATH

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(proto run pnpm -- store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: proto run pnpm -- install
