import { type GetOsVersionResponse } from "@api/command/os/GetOsVersionCommand";
import { DeviceModelId } from "@api/device/DeviceModel";

export const getOsVersionCommandResponseMockBuilder = (
  deviceModelId: DeviceModelId = DeviceModelId.NANO_SP,
  props: Partial<GetOsVersionResponse> = {},
): GetOsVersionResponse =>
  ({
    [DeviceModelId.NANO_SP]: {
      targetId: 856686596,
      seVersion: "1.1.1",
      seFlags: new Uint8Array([0xe6, 0x00, 0x00, 0x00]),
      mcuSephVersion: "4.03",
      mcuBootloaderVersion: "3.12",
      hwVersion: "00",
      langId: "00",
      recoverState: "00",
      secureElementFlags: {
        isPinValidated: true,
        hasMcuSerialNumber: true,
        hasValidCertificate: true,
        isCustomAuthorityConnectionAllowed: false,
        isSecureConnectionAllowed: false,
        isOnboarded: true,
        isMcuCodeSigned: true,
        isInRecoveryMode: false,
      },
      ...props,
    },
    [DeviceModelId.NANO_S]: {
      targetId: 858783748,
      seVersion: "1.1.1",
      seFlags: new Uint8Array([0xe6, 0x00, 0x00, 0x00]),
      mcuSephVersion: "6.4.0",
      mcuBootloaderVersion: "5.4.0",
      hwVersion: "00",
      langId: "00",
      recoverState: "00",
      secureElementFlags: {
        isPinValidated: true,
        hasMcuSerialNumber: true,
        hasValidCertificate: true,
        isCustomAuthorityConnectionAllowed: false,
        isSecureConnectionAllowed: false,
        isOnboarded: true,
        isMcuCodeSigned: true,
        isInRecoveryMode: false,
      },
      ...props,
    },
    [DeviceModelId.NANO_X]: {
      targetId: 855638020,
      seVersion: "2.2.3",
      seFlags: new Uint8Array([0xe6, 0x00, 0x00, 0x00]),
      mcuSephVersion: "2.30",
      mcuBootloaderVersion: "1.16",
      hwVersion: "00",
      langId: "00",
      recoverState: "00",
      secureElementFlags: {
        isPinValidated: true,
        hasMcuSerialNumber: true,
        hasValidCertificate: true,
        isCustomAuthorityConnectionAllowed: false,
        isSecureConnectionAllowed: false,
        isOnboarded: true,
        isMcuCodeSigned: true,
        isInRecoveryMode: false,
      },
    },
    [DeviceModelId.STAX]: {
      targetId: 857735172,
      seVersion: "1.3.0",
      seFlags: new Uint8Array([0xe6, 0x00, 0x00, 0x00]),
      mcuSephVersion: "5.24",
      mcuBootloaderVersion: "0.48",
      hwVersion: "00",
      langId: "00",
      recoverState: "00",
      secureElementFlags: {
        isPinValidated: true,
        hasMcuSerialNumber: true,
        hasValidCertificate: true,
        isCustomAuthorityConnectionAllowed: false,
        isSecureConnectionAllowed: false,
        isOnboarded: true,
        isMcuCodeSigned: true,
        isInRecoveryMode: false,
      },
      ...props,
    },
    [DeviceModelId.FLEX]: {
      targetId: 858783748,
      seVersion: "1.1.1",
      seFlags: new Uint8Array([0xe6, 0x00, 0x00, 0x00]),
      mcuSephVersion: "6.4.0",
      mcuBootloaderVersion: "5.4.0",
      hwVersion: "00",
      langId: "00",
      recoverState: "00",
      secureElementFlags: {
        isPinValidated: true,
        hasMcuSerialNumber: true,
        hasValidCertificate: true,
        isCustomAuthorityConnectionAllowed: false,
        isSecureConnectionAllowed: false,
        isOnboarded: true,
        isMcuCodeSigned: true,
        isInRecoveryMode: false,
      },
      ...props,
    },
  })[deviceModelId];
