name: "Setup toolchain with pnpm and build artifacts"
description: "Setup toolchain, restore pnpm dependencies, and download build artifacts"

runs:
  using: "composite"
  steps:
    - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-with-cache-composite@b83ec5020b992dcc53f683830e0abd2e147791ae

    - name: Download build outputs
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: build-outputs
