name: "Canonicalize package.json files"
description: "Canonicalize all package.json files according to RFC 8785 for deterministic JSON representation"

runs:
  using: "composite"
  steps:
    - name: Canonicalize package.json files
      shell: bash
      run: |
        # Create a temporary Node.js script for canonicalization
        cat > /tmp/canonicalize.js << 'NODE_SCRIPT'
        const fs = require('fs');
        const path = process.argv[2];
        
        function sortObjectKeys(obj) {
          if (obj === null || typeof obj !== 'object') {
            return obj;
          }
          
          if (Array.isArray(obj)) {
            return obj.map(item => sortObjectKeys(item));
          }
          
          const sorted = {};
          const keys = Object.keys(obj).sort();
          
          for (const key of keys) {
            sorted[key] = sortObjectKeys(obj[key]);
          }
          
          return sorted;
        }
        
        try {
          const content = fs.readFileSync(path, 'utf-8');
          const pkgJson = JSON.parse(content);
          const sorted = sortObjectKeys(pkgJson);
          const canonicalized = JSON.stringify(sorted, null, 2) + '\n';
          fs.writeFileSync(path, canonicalized, 'utf-8');
          console.log(`✅ Canonicalized: ${path}`);
        } catch (error) {
          console.error(`❌ Error processing ${path}:`, error.message);
          process.exit(1);
        }
        NODE_SCRIPT
        
        # Find all package.json files (excluding node_modules, lib, dist, etc.)
        find . -name "package.json" \
          -not -path "*/node_modules/*" \
          -not -path "*/lib/*" \
          -not -path "*/dist/*" \
          -not -path "*/.turbo/*" \
          -not -path "*/coverage/*" \
          | while read -r pkg_file; do
          
          echo "Processing: $pkg_file"
          node /tmp/canonicalize.js "$pkg_file"
        done
        
        echo "✅ All package.json files have been canonicalized"

