name: "[Sonar] Develop baseline"
on:
  push:
    branches:
      - develop

env:
  FORCE_COLOR: "1"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonar:
    name: Run tests and Sonar scan
    runs-on: ledgerhq-device-sdk
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-with-build-cache-composite@cc38a0dd9f30cf2f63ef50e4d857f0197003e23d

      - name: Tests
        id: unit-tests
        run: pnpm test:coverage

      - uses: sonarsource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8
        if: ${{ steps.unit-tests.conclusion == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
