name: "[Tests] ERC7730 Nightly"
on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup toolchain and dependencies
    runs-on: ledgerhq-device-sdk
    steps:
      - uses: actions/checkout@v6

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-with-cache-composite@develop

  build-libraries:
    name: Build libraries
    needs: [setup]
    runs-on: ledgerhq-device-sdk
    steps:
      - uses: actions/checkout@v6

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-with-build-cache-composite@develop

  erc7730-calldata-tests:
    needs: [build-libraries]
    uses: ./.github/workflows/cs-tester-reusable.yml
    with:
      runner: cs-tester
      tests: '["test:erc7730 1inch", "test:erc7730 aave", "test:erc7730 ethena", "test:erc7730 lido", "test:erc7730 lombard", "test:erc7730 poap", "test:erc7730 swissborg", "test:erc7730 tether", "test:erc7730 uniswap", "test:erc7730 velora", "test:erc7730 yieldxyz"]'
      devices: '["stax", "nanox", "flex"]'
      coin-app: Ethereum
      log-level: error
      enable-file-logging: true
      artifact-prefix: erc7730-calldata-logs
      summary-prefix: "ERC7730 Calldata Test"
    secrets: inherit

  erc7730-eip712-tests:
    needs: [build-libraries]
    uses: ./.github/workflows/cs-tester-reusable.yml
    with:
      runner: cs-tester
      tests: '["test:erc7730:typed-data 1inch", "test:erc7730:typed-data degate", "test:erc7730:typed-data ledgerquest", "test:erc7730:typed-data lens", "test:erc7730:typed-data lombard", "test:erc7730:typed-data opensea", "test:erc7730:typed-data permit", "test:erc7730:typed-data smartcredit", "test:erc7730:typed-data tally", "test:erc7730:typed-data uniswap", "test:erc7730:typed-data velora"]'
      devices: '["stax", "nanox", "flex"]'
      coin-app: Ethereum
      log-level: error
      enable-file-logging: true
      artifact-prefix: erc7730-eip712-logs
      summary-prefix: "ERC7730 EIP712 Test"
    secrets: inherit
