name: "[Automation] Generate SBOM"

on:
  push:
    branches:
      - develop
    paths:
      - "pnpm-lock.yaml"

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-toolchain-composite@develop

      - uses: LedgerHQ/device-sdk-ts/.github/actions/generate-sbom-composite@develop
