name: "[Automation] Generate SBOM"

on:
  push:
    branches:
      - develop
    paths:
      - "pnpm-lock.yaml"

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-with-cache-composite@131a330511ccc8af0a63548db27237ac029118e3

      - uses: LedgerHQ/device-sdk-ts/.github/actions/generate-sbom-composite@131a330511ccc8af0a63548db27237ac029118e3
