name: Generate SBOM

on:
  push:
    branches:
      - develop
    paths:
      - "pnpm-lock.yaml"

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-toolchain-composite@develop

      - uses: LedgerHQ/device-sdk-ts/.github/actions/generate-sbom-composite@develop
