name: "[Automation] Generate SBOM"

on:
  push:
    branches:
      - develop
    paths:
      - "pnpm-lock.yaml"

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-with-cache-composite@develop

      - uses: LedgerHQ/device-sdk-ts/.github/actions/generate-sbom-composite@develop
