name: "[Automation] Generate SBOM"

on:
  push:
    branches:
      - develop
    paths:
      - "pnpm-lock.yaml"

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-with-cache-composite@ac0b3fbcbc4e3fcb37970d9b2970b65efe23e30b

      - uses: LedgerHQ/device-sdk-ts/.github/actions/generate-sbom-composite@ac0b3fbcbc4e3fcb37970d9b2970b65efe23e30b
