name: "[Release] Publish Mock Server Docker Image"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to build from
        required: false
        default: develop

permissions:
  id-token: write
  contents: read

env:
  JFROG_REGISTRY: ${{ vars.JFROG_REGISTRY }}
  JFROG_REGISTRY_REPO: ${{ vars.JFROG_REGISTRY_REPO }}
  IMAGE_NAME: device-mock-server
  REF: ${{ inputs.ref || 'develop' }}

jobs:
  publish-mock-server-docker:
    name: Build and push Mock Server Docker image to JFrog
    runs-on: ledgerhq-device-sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ env.REF }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Get token from JFrog
        id: jfrog-login
        uses: LedgerHQ/actions-security/actions/jfrog-login@3868be0ef1ec8722fbdb2c6cda90f739cbfc742d # actions/jfrog-login-1

      - name: Login to JFrog OCI Registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4
        with:
          registry: ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REGISTRY_REPO }}
          username: ${{ steps.jfrog-login.outputs.oidc-user }}
          password: ${{ steps.jfrog-login.outputs.oidc-token }}

      - name: Read mock server version
        id: version
        run: echo "tag=$(jq -r '.version' apps/device-mock-server/package.json)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            --platform linux/amd64 \
            -f apps/device-mock-server/Dockerfile \
            -t ${{ env.JFROG_REGISTRY }}/${{ env.JFROG_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }} \
            .
