name: create release pull request
on:
  push:
    branches:
      - hack/wc-hackathon

env:
  FORCE_COLOR: "1"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/setup-toolchain-composite
      - name: install dependencies
        run: pnpm install
      - name: create release pull request
        uses: changesets/action@v1
        with:
          version: pnpm bump
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
