name: Create release pull request
on:
  push:
    branches:
      - release

env:
  FORCE_COLOR: "1"

jobs:
  version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: LedgerHQ/device-sdk-ts/.github/actions/setup-toolchain-composite@develop

      - name: build libraries
        run: pnpm build:libs

      - name: create release pull request
        uses: changesets/action@v1
        with:
          version: pnpm bump
          commit: "🔖 (release): Versioning packages"
          title: "🔖 (release) [NO-ISSUE]: Versioning packages"
        env:
          GITHUB_TOKEN: ${{ github.token }}
